#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
#------------------------------------------------------------------------------
# OpenFOAM 13: 流れに整列した blockMesh で移流(scalarTransport, D=0)。
# 斜めメッシュ版との比較用。流れは subSolverTime 0 で凍結。
#------------------------------------------------------------------------------
export FOAM_SIGFPE=false
chmod -R u+w constant/polyMesh 2>/dev/null
rm -rf constant/polyMesh log.*
find . -maxdepth 1 -type d -regex './[1-9][0-9]*' -exec rm -rf {} + 2>/dev/null

runApplication blockMesh
runApplication foamRun

touch post.foam
#------------------------------------------------------------------------------
